# Generated by Django 2.2.5 on 2019-09-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
